name: food
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.4+5
  firebase_database: ^2.0.3
  firebase_core: ^0.3.0
  cloud_firestore: ^0.9.0
  provider: any
  google_sign_in: ^4.5.4
  geoflutterfire: ^2.0.3+2
  geolocator: ^5.1.3
  location: ^2.3.5
  rxdart: any
  google_maps_flutter: ^0.5.11+1
  google_maps_webservice: ^0.0.18
  http: ^0.13.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - android/images2/
    - android/images2/chinese.jpg
    - android/images2/indian.jpg
    - android/images2/img2.jpg
    - android/images2/american.jpg
    - android/images2/french.jpg
    - android/images2/english.jpg
    - android/images2/img3.jpg
    - android/images2/img4.jpg
    - android/images2/r1.jpg
    - android/images2/r2.jpg
    - android/images2/r3.jpg
    - android/images2/r4.jpg
    - android/images2/logo.png
    - android/images2/in.jpg
    - android/images2/ind.jpg
    - android/images2/indi.jpg
    - android/images2/chi.jpg
    - android/images2/chin.jpg
    - android/images2/chine.jpg
    - android/images2/chines.jpg
    - android/images2/me.jpg
    - android/images2/mex.jpg
    - android/images2/mexi.jpg
    - android/images2/mexican.jpg
    - android/images2/tu.jpg
    - android/images2/tun.jpg
    - android/images2/tuni.jpg
    - android/images2/tunis.jpg
    - android/images2/tunisian.jpg
    - android/images2/it.jpg
    - android/images2/ita.jpg
    - android/images2/ital.jpg
    - android/images2/italian.jpg
    - android/images2/am.jpg
    - android/images2/americann.jpg
    - android/images2/re.jpg
    - android/images2/res.jpg
    - android/images2/rest.jpg
    - android/images2/resta.jpg
    - android/images2/profil.jpg
    - android/images2/background.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
